# Generated by Django 5.0 on 2025-06-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the item at the time of purchase', max_digits=10, null=True),
        ),
    ]
