# Generated by Django 5.2.1 on 2025-05-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('defective', 'Défectueux'), ('wrong_item', 'Mauvais article'), ('not_satisfied', 'Non satisfait'), ('other', 'Autre')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Demandé'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('refunded', 'Remboursé')], default='requested', max_length=20)),
                ('description', models.TextField()),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Retour',
                'verbose_name_plural': 'Retours',
            },
        ),
    ]
