# Generated by Django 5.0 on 2025-06-01 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sync_type', models.CharField(choices=[('product_catalog', 'Product Catalog Sync'), ('order_export', 'Order Export'), ('stock_update', 'Stock Update')], max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('partial_success', 'Partial Success')], default='started', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Summary message, e.g., errors or success count.', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Richer context, e.g., specific error details, processed IDs.', null=True)),
            ],
            options={
                'verbose_name': 'ERP Sync Log',
                'verbose_name_plural': 'ERP Sync Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FileUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(help_text='Stored file name/path after upload.', max_length=255)),
                ('original_file_name', models.CharField(help_text='Original name of the uploaded file.', max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel (XLSX)')], max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed_validation', 'Failed Validation'), ('failed_processing', 'Failed Processing')], default='uploaded', max_length=20)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list, help_text="List of errors, e.g., {'row': 5, 'error': 'Invalid SKU'}.", null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Upload Log',
                'verbose_name_plural': 'File Upload Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
