# Generated by Django 5.0 on 2025-06-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
