# Generated by Django 5.0 on 2025-06-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible product attributes like color, size, etc.', null=True),
        ),
    ]
